services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    deploy:
      resources:
        limits:
          cpus: '0.5' 
          memory: 512M  
        reservations:
          cpus: '0.1' 
          memory: 128M
    restart: always
